---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-rcon-password
  namespace: factorio
spec:
  encryptedData:
    rconpw: AgAGQSEcjEmWqL/Arx/1QWOi0QP6zUW/hLjNRFQUupkYys4riQAPSWjBTPxs4s0yI8xeuXaPYhgph6rA2oybF0VHI26ulGaSb9NI0dCaA0PtAuWuGfsBvGxSNdsXwgrPlm7p1iQC0/MDQhiW+t2CrpAYvDRPRygy05sCGzSM9Wbh83ltDyu7x6gXZS64RrDr20wWIcHMp11C5IGPCWEJcv7L3Oo4QCMW9JG/CibFTYSLBnqj0Co9bq/lrS4phwV16DZ+/pytGyvtL9xIcgTs7kQhd1lYD3DBgBQy1eRxajjvgCQTcNYKAh/rdNGJQnuFh4vXQfmiELNjUSKsWGqK9LPyfYs7JcCiWJWn+G7FCUStL3REV6DM7iXNTt/h/LmiI1fY3QHHLrvaYvWVaEPKHkk0yWmJ74nuYIyHDByL0y80KPHSf3eIyuHCIPjgVfV7aHso7JxvQDg8I26pfSFPa7Y0HotB83DoIG8CdWLUiqxt0t8n8ztwSp8mi9iUjZD3j3bfptjuIfZgPFAhFcIsuqcinFH/DzkZpzTFfIa4M4PZ6qLYSYsAq08FBN6RTg+CdmvLy8z7iQLrjo8IQx9Sbu56+py9pOO69v0fdO7PiU7QEV5mqvH1gK9ngOqPG2XrXGCvNvMDoKnoDxy4aN8yBbecNibq1aoLk7NQyeWlV5Rc+O0rXZ7D+Jg7Htwrm2/RU/piDBKTo5fGlrJ0caVV6Io923ZnKA==
  template:
    metadata:
      name: factorio-rcon-password
      namespace: factorio
