---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-server-password
  namespace: factorio
spec:
  encryptedData:
    game_password: AgAqm7RKc1vKNo5J7E+7pZ2pZXM1fc/AXZDyHo2RzWrGr1G6eI4B0R0R6JiK+XyJqXZIJ7EKIONy5iEcwMLNEwLSFxTZskCiR5nJLku9lnbadWb1urMdIDqQxhiAdiY5TtCnx+dEvN+mi2XZYDtObQ61us8fC3qlp2+mjMk1ZnSIKKH1UvoS8UiVroL2k5U15eFH9OqmXttz+o8XyOcu77Gf+R1OR7lFZD/7V2Z4l3N7iF8qJ4k6U3QceGHUVuBIplZTeEFRDxfJULFXoZIjMHupd9JqJJRPkcfBqltqCj3xXHxbUJK2DHgui1cCXr1YsUCZxB1JFTA5RdJGs8ULMZqXCuZknvyiFBd0BLmN7Vg63tAKryRqyuwC4ExNDJTXKxavqo0I0HvTsYPogJFc4Ouj0Anykl3cVOK+T6s70pgeE20CrMo1wz79sA9452ekbUqpAO+5D/WPdv4yVeZ5yrGozpNfFPsPcKEW2KaUtJy7sZAsk9PaDizDSm+7NGvfCeL9fT0vHI5JrQ94B8K6DaPvnfrtgG+EglU4dYRFht/kOrl6/DTvH3OR11r5B2E+tpvgCwVapeNLr/qCzbTBsjowh0kTaxYLbY1c0t7CnbmYKW2bAOfW4VRpeCT7FYBffzXt/RtMp4aOfbUcsfWIvKG2wC9tCcCKCxfXro7HL9MAYoAEBDWS2Uoy3XPuE8qvcONj6i992JZUGjYRbRvW
  template:
    metadata:
      name: factorio-server-password
      namespace: factorio
