---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: factorio
spec:
  encryptedData:
    .dockerconfigjson: AgB8XJ2iTJeV4Pn8tdmhIBIMD4bGiMrpNV810ymqfPWmZtsNwreMiW0BaIl2lVI6vSu1YSWZllAxKwE/56irGVx8+aRI+lSOHuxgGWGuyx8/RV77xLYeQKcy1eke0YNSQIaGPMEuh0h8XhgNZxxNWfIHdVohMpJsW6jmc2lcQ4e6vvWzyFYS+JW2ncsV+aLtvWeWJD6u+oSeAOdZcE5a7ToKbU/LoJUujs+vb75RIs282S5InrjStc7Fs4ey7NnqEghUFOoDxZsplrC/4WHumGyWUG/JUQGFrXPS2BeM1gMsl8FP4W4+KEiq/W/nZMffb5O23dvHsGsV7z9C/VpIPqQ3dlG9OuYmrMGbSFzqkmq09tsNbnfQ3HBr1wNB8UL2rkXOc8tZIouRT0rbQ3Ruxc8MEMWQyikHy/p9qrzwLv6Mi4Bft4fraC4cWcpiq+3eNcJs1my+hgaA0mpqyDz2zF/fP5wYYymAHsLjwO8tWLkMvKcd0XoJB76dCp3He/ExaAC/PM4TciCllapOlbX1N2C1WaX76otTt04+DT4AOM0dDVNn9C4vwUqSn7yJOxyXwTDhxdJyKUFkchhv99gEpbA5CT0LsO5jamQFHRbPBTPUp8f84KtuxkussuaHMVl1IqphRGN2qv4HqIX15PrXXMuHvofVT0rlaQy/eAhTMhIwYjNiW3SNNJ9KKhXHPFCBWgZoBJlEuxVfUJAkA1T1e2ydxA7dj+3QTsrS5nUfnrqSaO5UTCQSxeSbDTF6tY+B91N170VLRRZbRmj900uSzLizVxyHIdC2Xvo97Cu85JwixTMCG9dZ+/daoEyI7X55XforiF3k2tZo81ZVPASVaW0q+ov2OCWvxBg9I3zo98OpR3EQ8m03lsgR5aoVMb1/QJBECAgYHm2tdxbAL6F0N1L/EdhuHB84AGnw+xBZmRuFEa/4TaPfsKucEo4=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: factorio
    type: kubernetes.io/dockerconfigjson
