---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-user
  namespace: observability
spec:
  encryptedData:
    ADMIN_PASSWORD: AgAb+JSJtgUmXn7/TlzdB4bXmpeE69RG2AGBXZm71gkFdRIEerSKPlwIHjuo7I6kWeow9nFrbhB24R4+aBz7+im46eHvXGgCoozZ2Q0aDVYSd57wgTsGTwYpYaiWo5VJ1ugcqOm/mRK4kKsLRVEMsdGc423sKUavrWBF4CCNUNBx1xhIzHR/7vXSF1lUq1ezqjPYW2vvI2niiyKxBY6GX/d663Gej4+FZaVMbKmrAGQ+0NeYVFwbF7AshEGyI+my/Daf0e/Ka4J+O6+b57cv3ooPXlBnBF1B1qDUz1Ul7/ZEekXqtSd5qJ7Gft1zwlaDwowkYpSGiVqo92qKzsRct1mZJw3VHzwXPULE0adzfjoXx0DS5tYPJ0YkvLDnRSX4XIdsfPkbvj2zrx2RwtqxjiqZZToww6kbHlZOgUyikZmaphzNQipIiNavCGse0XsYpL7W1HE0UlB/ODAyJR1HeC9VjVD/gnJTHWuLempd46nWmJ6QKCtBQObKvHT6CmiWHkHEsMIaclwq50ek0PejK/O/GqiS2eDRsnl3kB7ccbYE4+X7roVbks96xS5qB5JnvGUQHkijfkUPGpzsjQO6sXVGcGVzPxFdhRhf4T6e31VzbfS/vbF9u2+8sbyqWl5sRAV8NJqM4HPa9x2xAmtqJkS+Ri5t//j6h3N5sJZOLa5qpF9ZQ9mxdlEzrMsahzfVfFfZvOujeeFyRleQLWazc0vR1U2XU3U=
    ADMIN_USER: AgB9Xl/yzBTALf5BfAwvax4vNicH4ltY2PyJs2VHq+y1IKUXM/I3jVlEdJngXHjJPYd+hvuA+xJo+J7ZoSrFtjOryIFNUR6i1YUQ/lQRwK6PX7FZLAcjeDi5Uxf38XnREapX0WPLt3GNHi8xF8jodzjqPHsHUHn2Eoxptoc+ch9udVwiqkzl5kPY9ub3VThMMv6q2m1kDsFD+tsXAtYUatOf8k2IvlBSa2D5DBr3OG47wWQH2EG9+Y3qVbraQFgabHFIC/QTmKEyw3xBFKvZ4Uy4V1GLKqzM+OL6DCdxKsIyo7rhh36SvU6ORraqOfBIGtVhI9GyTvU558ry3vqhpxeQz8qN+79gAPbPBhzGvEsfWo609CY2SlKgX/llDTkw5XQpgJsAIqRGDguqNSzIbXEbIEv15JnP1p/XAxTanXaJ4tDjOt88K09bIox5eOxc9rppm1HHEmQ4/mKldNGhOB81snII7ufC1wferkwXXtFVm3xV2s/0884Qvcq8rNG8anqhYBQAx53kMWyeYQAb1s17r8ofQtMWpXTyi9D3+f1emj50wQm2+CIMt2RRPo+OPKSqzt0O+axL6NFL/YyoDrWRR0xFhgo7bJ9fXQai+lyQUVxjHR5mimVarWJMRjiDo1e705IYUqEALbqeU/MAGGswuAr5aO1P7Dztjzh3wliw7SzCJqQtxrRBESG0Yq/JfIy2cPwcK/X1lJDlXn7C
  template:
    metadata:
      name: grafana-admin-user
      namespace: observability
