---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgBIppA9HfKhjqGsidvOeKFf9TFsrdIPTLZtojOcjapBQM/peLPyx4pfLS8/SUhXQefUcc0tOHUXnmeZuwtS6n8iOePw/LmpR3Tge+KVcPe5cfBi5KVsOlYw4sypGDmNCO0sdcKW8KU95S7Xk0YGmysMzExMGBt9V4Q7p+mry/W84WDBZko+fxbP2wS1wO3Hq2knF20LpfIASmqHuUZFTT/BmaG/07u2btomNCd39ndR4uPojIIJx1sMeag4sI9FUY8nxbkNwtoLjq6i8OD23o9LTZqAKTiBI0EvslNmzTt5Hphzl4b7yJNwACyK10VCrMx34/vGVldJLMkSTUSyZNvD0dZYipxlEXmRlmdcG6lmZ5Q6uRatbyZxMRzMljKy9E9O7NWhfeztYm7xTuk9OfHpjGE81YGi8NpqiOPJkwhCe9iV/PqZetM9zQgv06q1GE/D986J4t9e7dLtWMg+aO2FhBsnC5NPhzOqIbDRPmuI7bXX5LMU/Xs7ISB9VSH5Otp8/CRpA9wL2r7+1EkvbNouUBAr1daqOrKuB+gKyEQRkAd+5DLFJ9ULla9GeGRPEeqCcbwrOPxZJvdB2oxQ6iR4ZJdDJyoadt2nsB6WZgF+Ws0g8BPNtCPA8jG0kEdZVRhkJ+IYIuo74QWXHFeXM6IBncdZ8oN2xxfu9qfKKQ895hdruq5aYvC/dhn9NXbgm90qBsczVjY7Xhuef0HHsbYnuIcf4g==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgCwl50hFD+yhjtJff9sjhRifRe4hXnIh4FnUnNIifv7IbUq21b1v58slNSS6ZgG13v7UAVDlrus+FnEpYlwE1YiVc89M3j64bT/wAbUVBaFRJOA0pajd3dGTCJ0Udx14YBe9Ts6jlndAZf+NFWCCIG8fNAHAArSH7tDjK1+7LketkMlTbA6+RfkiysEbUPO55uYG+8c57UpZA5bO3UUa+XvUOCsP/ghWtm0OzmD7hT2/AVmPo4G089VEFf53TNsOlP/fluPgtkWaiodGIQ1HjKlDxXEXvbt7/N8/eiw5/s9h0xSxPY0DroZcUYp2OjP3G3HRtRp3NFiOjs/jTNt3wBZRrcmwJw/tFb0kbGbou6KlmEFIAxcty3ofXNjaj60cvkBqoxjCr9bAcNrM3ouR26nQYV4o+J5V1PL8W2+zHWD9b8Dv74JBz4gzwEiqk4Js5jW+Z2g2nWB4fzSXwValSq2AFLuAn6DvODICl/MeE0U95yZCiPoEY5T3PSczDeALTH9TmbKg80ZVmYERaLJp/oEeDbdrP4ipttt+8M3CyYE3fPKn/Br1jEYNF9s3QPRt2U4ubVx15Eu5gSZhYuX3No1WWvu5o0hJBtgRzvW1wV07yzBRkzHPwarxnJ/d8i0yoCdPf43D/oBioCR6MHKOajuMoOwM/Y5+KKl4TYkVFlvMYmXVvJRjD0/+nN/7A3OTR/8UcNfE4WjoL4SMp6GnjYbNQBPRXajwMUeFDyColEZQtrGw8bDAfzP
  template:
    metadata:
      name: grafana-github-oauth
      namespace: observability
