apiVersion: v1
kind: Secret
metadata:
  name: skkuding-aws-credentials
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "aws-credentials/skkuding-aws-credentials"
type: Opaque