apiVersion: v1
kind: ServiceAccount
metadata:
  name: factorio-exporter
  namespace: factorio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: factorio-exporter
  namespace: factorio
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: factorio-exporter
  namespace: factorio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: factorio-exporter
subjects:
  - kind: ServiceAccount
    name: factorio-exporter
    namespace: factorio
