apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-rcon-password
  namespace: factorio
spec:
  encryptedData:
    rconpw: AgBYoPgobx+KSzx730ZOccRDbo3DuhEqZtecsg9LIIXKgE/Yd9mwo7Oi83TDSNYlFCoY9/vIAIjxFTDqXObFBnTsxYAkCJ3liwZS3xJqF+HQiYZ2YKYg5mNSDj/ZQkRYHRw84oBztLgdzF4NspCLAck0xvxgdWZ+V1Anf7CA4rm9yIS89CHVLzCh4RlLOJHKP4+almM8PBKi5lrvOpK53NYf7vdy3KBsEWleb0tbjhpSm3OgI2/87JQoTxvmbRFBhn+3/li8B5FSejT9hJfP5E5y71Kc7rJgav2R0CtVFl7UqaI8oLy3oIaJnD8pSBDuiIYppJcII3EIuRpcnzZyPksSjKzd4Sd35QFkBKOcXzvGaOue6gdJFg2ageUjeGvg+Tly/R0W5UmTxkhRZcns8BsGw8CAt3ijQFWy7cOianqe2AjMbQm/p0JG7A9foYFzRH27ck8o7C+QRpKgwYc9vfeak2Jyr+PcVYidj7vqE7Axxcvqhpmayw2gDjNSaXXM7iHnn2PIYQ2Oi/2O7yemy5C9HjGyxr8DgpicTiTEDdQEga33NyPzPdIxKCKcEb+FCUsHmc5zZAJsJE2dN6z1qtyGf+N57A78e4m+4dSH8kpmsMU9+RLjvp811dPsnSfbz5hzdxUPKNQIQrNUOn337xR0O7JoCS31hipEvPkSIGmuOkASi4EunPBCaMr9e62TYL3AwBMowUnLB5MwDfMzDYbOpN6isYEU5mo=
  template:
    metadata:
      name: factorio-rcon-password
      namespace: factorio
