---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-server-password
  namespace: factorio
spec:
  encryptedData:
    game_password: AgC5ZOL3ZhxZrwcka9ZKWWaxbXJM9IRYi0+Ka4IQo9lgfRV6RL6YV3t1DWltf91aXHG4jp5u6ymULaWoqCTttafEEaCVnP20dwIbBAFlTR0CsbI4WF5zGiRyYnq6L8rrFw9ka/nWS3u2/spCaDOMFOLox6yPBH8qeEBfJ32arOIFuOsBXu4GsrkPXhZNMh3bgG2EEvoHTzgsMJUikEBG3i7sCnDT7VWxtsZ197TkgCs4ahzCpJCSa3Pb7h7mjNTLZ451eiR8kjyVM08qGTF7EcA3evSfL5Cgk3vTXZdJqZB09XEPVbY2mubBD0U7fj6YpV2SY49u7yCrzCi7LR73OZ3GT/LDwnkgIHjxciRZutTQXSNdfzN2xH6zn52JNGZqojQSo6OBW+6uszoksTD3+9dmgjN3pV3i/p9+WlZQnkpUOa38Y0ztVwh4FVfu3bvSEc2qlcsBURzX1F/kif0yKgQJweMf5DgBnjcyCjjXEisHSjIDDLthKzHeaiFqZzzAV9DqHfOUSSqVGVb1vAAsbCpu3FH6ic5bfTVDRu1TSdFvz/x1kND+6B8zTWGrDZBKmzqEz8Yg+/01S7i+KBiufaMg7KmvSEmffP2TVNl4kXYBNbUpXJvCh2jI3e5hS09KAOq4bXaoXJEAoJEPrTJW6wKeKXRrhyOR5RYnHgVPI6AA2YEZcCgNoUp+gjDOKJIRHiiU4XWK8CvGgN7FPKtQ
  template:
    metadata:
      name: factorio-server-password
      namespace: factorio
