apiVersion: v1
kind: ServiceAccount
metadata:
  name: factorio-chat-bridge
  namespace: factorio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: factorio-chat-bridge
  namespace: factorio
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: factorio-chat-bridge
  namespace: factorio
subjects:
  - kind: ServiceAccount
    name: factorio-chat-bridge
    namespace: factorio
roleRef:
  kind: Role
  name: factorio-chat-bridge
  apiGroup: rbac.authorization.k8s.io
