apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      targetRevision: "5.0.0"
      helm:
        valueFiles:
          - $homelab/k8s/minecraft/values.yaml
    - repoURL: https://github.com/manamana32321/homelab
      targetRevision: main
      ref: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
