apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: amang-api
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: production
            branch: main
          - env: staging
            branch: main
  template:
    metadata:
      name: api-{{env}}
      namespace: amang-api-{{env}}
    spec:
      destination:
        namespace: amang-api-{{env}}
        server: https://kubernetes.default.svc
      source:
        path: 'infra/k8s/api/overlays/{{env}}'
        repoURL: https://github.com/skku-amang/main
        targetRevision: '{{branch}}'
        directory:
          recurse: false
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
