apiVersion: v1
kind: ConfigMap
metadata:
  name: fsm-config
  namespace: factorio
data:
  conf.json: |
    {
      "server_port": "80",
      "secure": false,
      "sq_lite_database_file": "/opt/fsm-data/sqlite.db",
      "log_file": "/opt/fsm-data/factorio-server-manager.log",
      "autostart": false
    }
  server-settings.json: |
    {
      "name": "JSON",
      "description": "JSON Factorio Space Age Server",
      "tags": ["space-age", "private"],
      "max_players": 0,
      "visibility": {"public": false, "lan": true},
      "username": "",
      "password": "",
      "token": "",
      "game_password": "ilovefactorio",
      "require_user_verification": false,
      "max_upload_in_kilobytes_per_second": 0,
      "max_upload_slots": 5,
      "minimum_latency_in_ticks": 0,
      "ignore_player_limit_for_returning_players": false,
      "allow_commands": "admins-only",
      "autosave_interval": 5,
      "autosave_slots": 20,
      "afk_autokick_interval": 0,
      "auto_pause": true,
      "only_admins_can_pause_the_game": true,
      "autosave_only_on_server": true
    }
  map-gen-settings.json: |
    {
      "terrain_segmentation": 1,
      "water": 1,
      "width": 0,
      "height": 0,
      "starting_area": 1,
      "peaceful_mode": false,
      "autoplace_controls": {
        "coal": {"frequency": 1, "size": 6, "richness": 1},
        "stone": {"frequency": 1, "size": 6, "richness": 1},
        "copper-ore": {"frequency": 1, "size": 6, "richness": 1},
        "iron-ore": {"frequency": 1, "size": 6, "richness": 1},
        "uranium-ore": {"frequency": 1, "size": 6, "richness": 1},
        "crude-oil": {"frequency": 1, "size": 6, "richness": 1},
        "trees": {"frequency": 1, "size": 1, "richness": 1},
        "enemy-base": {"frequency": 1, "size": 1, "richness": 1}
      },
      "seed": null
    }
