# Rate limit 해제됨 - 재시작 방지를 위해 restartPolicy 관련 설정 추가
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-server-manager
  namespace: factorio
  labels:
    app: factorio-server-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio-server-manager
  template:
    metadata:
      labels:
        app: factorio-server-manager
    spec:
      containers:
        - name: factorio-server-manager
          image: ofsm/ofsm:latest
          imagePullPolicy: Never
          ports:
            - name: game
              containerPort: 34197
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: FSM_SECURE
              value: "false"
          volumeMounts:
            - name: fsm-config
              mountPath: /opt/fsm/conf.json
              subPath: conf.json
            - name: fsm-config
              mountPath: /opt/factorio/config/server-settings.json
              subPath: server-settings.json
            - name: fsm-config
              mountPath: /opt/factorio/config/map-gen-settings.json
              subPath: map-gen-settings.json
            - name: fsm-data
              mountPath: /opt/fsm-data
            - name: factorio-saves
              mountPath: /opt/factorio/saves
            - name: factorio-mods
              mountPath: /opt/factorio/mods
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
      volumes:
        - name: fsm-config
          configMap:
            name: fsm-config
        - name: fsm-data
          persistentVolumeClaim:
            claimName: fsm-data
        - name: factorio-saves
          persistentVolumeClaim:
            claimName: factorio-saves
        - name: factorio-mods
          persistentVolumeClaim:
            claimName: factorio-mods
