apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factorio-server-manager
  namespace: factorio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - factorio-admin.json-server.win
      secretName: factorio-admin-tls
  rules:
    - host: factorio-admin.json-server.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: factorio-server-manager
                port:
                  number: 80
