apiVersion: v1
kind: Service
metadata:
  name: factorio-server-manager
  namespace: factorio
  labels:
    app: factorio-server-manager
spec:
  type: NodePort
  selector:
    app: factorio-server-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: game
      port: 34197
      targetPort: 34197
      nodePort: 34197
      protocol: UDP
