apiVersion: v1
kind: Service
metadata:
  name: factorio-server-manager
  namespace: factorio
  labels:
    app: factorio-server-manager
spec:
  type: ClusterIP
  selector:
    app: factorio-server-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
