---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: factorio
spec:
  encryptedData:
    rootPassword: AgDBMOHsMNj5YhvvmE8WnuD5NtyYNURxrJZUAJSjstzzLtoXVgC6HCe6V2n5J1m+3AjmbW26km3cI4kp1/z5jZTmSpyqfDzrBZ6dI6d9RUfejafvRVW+a6GaGhqYIKxy9WRz3EDt586b+uNscMy64Z8JOKz82DpYSkCbf3Ap9F5EpeIJVGMtIoMPRX6VxDZzGQ+5gyjDAXLWv+HwajzzUY4WJznCfz9DNBNONWWJlbrpakldKAYL2L+QXa2QG+kfS4Wfdy3O9HCW0Qp2MF7cRgCiiWI8/1PbgdCOvTyQs9G5dxosxkjjaEh6rbcv+GNrOEEF7hKft4f5X2+ZSb45/7oJYNLpn2Zv4ww7KTxmih68zLYTzF1oTm5XWXYwF8q7OhRJmajhPp0CiJ0AVIYA2QRMQnOJFj3Gh3aQFjDlFJTNFRIbidnfg4WuYzkGkvo5Qs8+Nq5gz4QGcr/tR46fYHbRlRG3L00KBwoPvzCFwzzWbNxvtJeRMtUralpUFu4XeRJeijCyuLgNnBrwDySqCbXia3vk/CdVCAwmcYV3Db9eOdyuEe1JTS1bOcxhHayIxMN/kF1NS8wsAIxFWFHgElcS2IXAN1biikOxjgQYAbPBkqwQHuWeiFk7JsFGvN9UkimEUyqWg/65ooUjBZrs/UsOOfPWeq4grtY+aZ0YfbEpOrBja7hr+x5JjRjjAHz007UHV49MpQh7Oob+s1Y8b5TMML1Dl29CqddcM/GZ3AGBqQ==
    rootUser: AgCMmAoD6XYWDq3Ifaizbo+OxHciUf4lbCoqZrXtNw1DbIf4WiiEsgMz5l1r70YwbvKpati+biNoYGBRpzEGcHAnJyhe3GXUp2QXWt82vlJvpiJFe3VDEPy859X6gj4E+2YEHGLGeWWQelZooMuWCD322cq1GfRVmr7lMLPSvbfk8FTWHxKAYZGtLZ44P/aYeZtrcSCdB0MaE2U0JA+k4BO9Xa8HAt7okg6qQ2byIp1ZmVE430LDqw8ejZYArZlLDU7QVenLIeZWmJsOw3L0XrKNOe8c4IUGiO/wm8051SqjnR7Vm32lhK3R7Nw8sChtE3Lz0ZQZr7LzXJkKpZX7duUUWgrs7tz8MOgHC66aInqx0FRaooRsCQAui15XNTlcePCb/o46uV3fCuDR/Zn5ZXbMx3tlQFBg+8Y3Qw1HK9AkSgpr4O0Wg4DmuBlUl/Egc6R5tc6mlutP5mKAOW8vrXx4B1G+XL5vbVZDA6QXB6orEKU3Zr1h9cpRTIzDJ6/xAO1cfQbYDggMU6JYzoLrAY7fNe4pjTmKMmtQmFi3wnu5oDu/ecILqCD8WbWz+OrQ4VbjfZ/gp6MPHdpD7Clb5WFz3zHYiixZk/OUQEnC2GEmHH/HGB8CG5suJoyz8cBB/D2BgozmpvwSlRlTZRvn+dJWkJqSyMolsjonzacq6YClLH9usFKJTsvsz4ocmu5C1GGvsuMb8gyxQ94y
  template:
    metadata:
      name: minio-credentials
      namespace: factorio
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    type: Opaque
